AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
